extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:prettier/recommended
env:
  browser: true
  es6: true
  node: true
  jest: true
plugins:
  - react
  - prettier
parserOptions:
  sourceType: module
  ecmaVersion: 12
  ecmaFeatures:
    - jsx: true
settings:
  react:
    version: detect
rules:
  prettier/prettier: error
  react/prop-types: 0 
  react/no-unescaped-entities: 0
  react/react-in-jsx-scope: 0
