extends:
  - eslint:recommended
  - plugin:prettier/recommended
env:
  browser: true
  es6: true
  node: true
  jest: true
plugins:
  - prettier
parserOptions:
  sourceType: module
  ecmaVersion: 12
rules:
  prettier/prettier: error
  no-unused-vars: 
    - error
    - argsIgnorePattern: next
